export default function handler(req, res) {
  if (req.method === 'GET') {
    res.status(200).json({
      destinations: [
        {
          Title: 'Egypt',
          Img: 'https://images.pexels.com/photos/1738536/pexels-photo-1738536.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
          Details: [
            {
              title: 'Nubia Aqua Beach Resort',
              stars: 5,
              date: '18.11.2022',
              price: 2399,
              priceDiscounted: 2999,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 1',
              stars: 4,
              date: '19.11.2022',
              price: 2000,
              priceDiscounted: 2500,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 2',
              stars: 4,
              date: '19.11.2022',
              price: 2000,
              priceDiscounted: 2500,
              IsLastMinute: true,
              IsAllInclusive: false,
            },
            {
              title: 'Placeholder Title 3',
              stars: 4,
              date: '19.11.2022',
              price: 3000,
              priceDiscounted: 3500,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 4',
              stars: 4,
              date: '19.11.2022',
              price: 1500,
              priceDiscounted: 5500,
              IsLastMinute: false,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 5',
              stars: 4,
              date: '19.11.2022',
              price: 7000,
              priceDiscounted: 8000,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
          ],
        },
        {
          Title: 'Greece',
          Img: 'https://images.pexels.com/photos/1285625/pexels-photo-1285625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
          Details: [
            {
              title: 'Nubia Aqua Beach Resort',
              stars: 5,
              date: '18.11.2022',
              price: 2399,
              priceDiscounted: 2999,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 1',
              stars: 4,
              date: '19.11.2022',
              price: 2000,
              priceDiscounted: 2500,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 2',
              stars: 4,
              date: '19.11.2022',
              price: 2000,
              priceDiscounted: 2500,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 3',
              stars: 4,
              date: '19.11.2022',
              price: 4180,
              priceDiscounted: 5670,
              IsLastMinute: false,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 4',
              stars: 4,
              date: '19.11.2022',
              price: 3333,
              priceDiscounted: 4352,
              IsLastMinute: false,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 5',
              stars: 4,
              date: '19.11.2022',
              price: 4444,
              priceDiscounted: 5555,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
          ],
        },
        {
          Title: 'Turkey',
          Img: 'https://images.pexels.com/photos/2048865/pexels-photo-2048865.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
          Details: [
            {
              title: 'Nubia Aqua Beach Resort',
              stars: 5,
              date: '18.11.2022',
              price: 2399,
              priceDiscounted: 2999,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 1',
              stars: 4,
              date: '19.11.2022',
              price: 1800,
              priceDiscounted: 3900,
              IsLastMinute: false,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 2',
              stars: 4,
              date: '19.11.2022',
              price: 4500,
              priceDiscounted: 5500,
              IsLastMinute: true,
              IsAllInclusive: false,
            },
            {
              title: 'Placeholder Title 3',
              stars: 4,
              date: '19.11.2022',
              price: 2200,
              priceDiscounted: 2800,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 4',
              stars: 4,
              date: '19.11.2022',
              price: 2100,
              priceDiscounted: 3000,
              IsLastMinute: true,
              IsAllInclusive: true,
            },
            {
              title: 'Placeholder Title 5',
              stars: 4,
              date: '19.11.2022',
              price: 2500,
              priceDiscounted: 2900,
              IsLastMinute: true,
              IsAllInclusive: false,
            },
          ],
        },
      ],
    });
  } else {
    // Handle request methods other than GET
    res.setHeader('Allow', ['GET']);
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
}
